<body>
<ul>
			<li>
			<a id="letter_a" href="/letra/a.html" title="9398 artistas com a letra A">A</a>
		</li>
			<li>
			<a id="letter_b" href="/letra/b.html" title="8996 artistas com a letra B">B</a>
		</li>
			<li>
			<a id="letter_c" href="/letra/c.html" title="7184 artistas com a letra C">C</a>
		</li>
			<li>
			<a id="letter_d" href="/letra/d.html" title="6765 artistas com a letra D">D</a>
		</li>
			<li>
			<a id="letter_e" href="/letra/e.html" title="3904 artistas com a letra E">E</a>
		</li>
			<li>
			<a id="letter_f" href="/letra/f.html" title="4775 artistas com a letra F">F</a>
		</li>
			<li>
			<a id="letter_g" href="/letra/g.html" title="4999 artistas com a letra G">G</a>
		</li>
			<li>
			<a id="letter_h" href="/letra/h.html" title="2913 artistas com a letra H">H</a>
		</li>
			<li>
			<a id="letter_i" href="/letra/i.html" title="2366 artistas com a letra I">I</a>
		</li>
			<li>
			<a id="letter_j" href="/letra/j.html" title="4933 artistas com a letra J">J</a>
		</li>
			<li>
			<a id="letter_k" href="/letra/k.html" title="3198 artistas com a letra K">K</a>
		</li>
			<li>
			<a id="letter_l" href="/letra/l.html" title="5836 artistas com a letra L">L</a>
		</li>
			<li>
			<a id="letter_m" href="/letra/m.html" title="9744 artistas com a letra M">M</a>
		</li>
			<li>
			<a id="letter_n" href="/letra/n.html" title="3496 artistas com a letra N">N</a>
		</li>
			<li>
			<a id="letter_o" href="/letra/o.html" title="2309 artistas com a letra O">O</a>
		</li>
			<li>
			<a id="letter_p" href="/letra/p.html" title="5343 artistas com a letra P">P</a>
		</li>
			<li>
			<a id="letter_q" href="/letra/q.html" title="395 artistas com a letra Q">Q</a>
		</li>
			<li>
			<a id="letter_r" href="/letra/r.html" title="5172 artistas com a letra R">R</a>
		</li>
			<li>
			<a id="letter_s" href="/letra/s.html" title="8658 artistas com a letra S">S</a>
		</li>
			<li>
			<a id="letter_t" href="/letra/t.html" title="7515 artistas com a letra T">T</a>
		</li>
			<li>
			<a id="letter_u" href="/letra/u.html" title="978 artistas com a letra U">U</a>
		</li>
			<li>
			<a id="letter_v" href="/letra/v.html" title="2471 artistas com a letra V">V</a>
		</li>
			<li>
			<a id="letter_w" href="/letra/w.html" title="1915 artistas com a letra W">W</a>
		</li>
			<li>
			<a id="letter_x" href="/letra/x.html" title="384 artistas com a letra X">X</a>
		</li>
			<li>
			<a id="letter_y" href="/letra/y.html" title="896 artistas com a letra Y">Y</a>
		</li>
			<li>
			<a id="letter_z" href="/letra/z.html" title="1072 artistas com a letra Z">Z</a>
		</li>
			<li>
			<a id="letter_0" href="/letra/0.html" title="760 artistas com a letra 0">0</a>
		</li>
	</ul>
</body>