<body>
	<h2>Músicas mais populares</h2>
	<div class="cloud">
													<a class="cloud2" alt="A Carta - Letras,cifras e m&uacute;ica" title="A Carta - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/eduardo-costa/a-carta.html">A Carta</a>
											<a class="cloud0" alt="A Mulher Que Eu Amo - Letras,cifras e m&uacute;ica" title="A Mulher Que Eu Amo - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/roberto-carlos/a-mulher-que-eu-amo.html">A Mulher Que Eu Amo</a>
													<a class="cloud1" alt="Alejandro - Letras,cifras e m&uacute;ica" title="Alejandro - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/lady-gaga/alejandro.html">Alejandro</a>
													<a class="cloud3" alt="Baby - Letras,cifras e m&uacute;ica" title="Baby - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/justin-bieber/baby.html">Baby</a>
													<a class="cloud2" alt="Bad Romance - Letras,cifras e m&uacute;ica" title="Bad Romance - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/lady-gaga/bad-romance.html">Bad Romance</a>
											<a class="cloud0" alt="Bala De Prata - Letras,cifras e m&uacute;ica" title="Bala De Prata - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/fernando-e-sorocaba/bala-de-prata.html">Bala De Prata</a>
													<a class="cloud2" alt="Borboletas - Letras,cifras e m&uacute;ica" title="Borboletas - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/victor-leo/borboletas.html">Borboletas</a>
													<a class="cloud1" alt="Chora,me liga - Letras,cifras e m&uacute;ica" title="Chora,me liga - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/joao-bosco-e-vinicius/chorame-liga.html">Chora,me liga</a>
													<a class="cloud3" alt="Chuva Chover - Letras,cifras e m&uacute;ica" title="Chuva Chover - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/paula-fernandes/chuva-chover.html">Chuva Chover</a>
													<a class="cloud1" alt="Complicado Demais - Letras,cifras e m&uacute;ica" title="Complicado Demais - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/paula-fernandes/complicado-demais.html">Complicado Demais</a>
													<a class="cloud2" alt="E Daí - Letras,cifras e m&uacute;ica" title="E Daí - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/guilherme-e-santiago/e-dai.html">E Daí</a>
											<a class="cloud0" alt="Gypsy - Letras,cifras e m&uacute;ica" title="Gypsy - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/shakira/gipsy.html">Gypsy</a>
													<a class="cloud4" alt="Hey, Soul Sister - Letras,cifras e m&uacute;ica" title="Hey, Soul Sister - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/train/hey-soul-sister.html">Hey, Soul Sister</a>
											<a class="cloud0" alt="Jeito De Mato - Letras,cifras e m&uacute;ica" title="Jeito De Mato - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/paula-fernandes/jeito-de-mato.html">Jeito De Mato</a>
											<a class="cloud0" alt="Levo Comigo - Letras,cifras e m&uacute;ica" title="Levo Comigo - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/restart/levo-comigo.html">Levo Comigo</a>
													<a class="cloud4" alt="Madri - Letras,cifras e m&uacute;ica" title="Madri - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/fernando-e-sorocaba/madri.html">Madri</a>
													<a class="cloud3" alt="Meteoro - Letras,cifras e m&uacute;ica" title="Meteoro - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/luan-santana/meteoro.html">Meteoro</a>
													<a class="cloud3" alt="Meu Eu Em Você - Letras,cifras e m&uacute;ica" title="Meu Eu Em Você - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/paula-fernandes/meu-eu-em-voce.html">Meu Eu Em Você</a>
													<a class="cloud4" alt="Passaro De Fogo - Letras,cifras e m&uacute;ica" title="Passaro De Fogo - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/paula-fernandes/passaro-de-fogo.html">Passaro De Fogo</a>
													<a class="cloud1" alt="Pra Não Morrer De Amor - Letras,cifras e m&uacute;ica" title="Pra Não Morrer De Amor - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/bruno-e-marrone/pra-nao-morrer-de-amor.html">Pra Não Morrer De Amor</a>
													<a class="cloud3" alt="Quero Sim - Letras,cifras e m&uacute;ica" title="Quero Sim - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/paula-fernandes/quero-sim.html">Quero Sim</a>
													<a class="cloud2" alt="Sem Você - Letras,cifras e m&uacute;ica" title="Sem Você - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/paula-fernandes/sem-voce.html">Sem Você</a>
													<a class="cloud4" alt="Stereo Love (feat Maya) - Letras,cifras e m&uacute;ica" title="Stereo Love (feat Maya) - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/edward-maya/stereo-love-feat-maya.html">Stereo Love (feat Maya)</a>
													<a class="cloud1" alt="Tik Tok - Letras,cifras e m&uacute;ica" title="Tik Tok - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/ke$ha/tik-tok.html">Tik Tok</a>
													<a class="cloud4" alt="Your Love Is My Drug - Letras,cifras e m&uacute;ica" title="Your Love Is My Drug - Letras,cifras e m&uacute;sica" rel="tag" href="/musica/ke$ha/your-love-is-my-drug.html">Your Love Is My Drug</a>
		</div>
	<div class="footer"><a href="/top/musicas.html" title="TOP 100 M&uacute;sicas Mais Acessados">TOP 100 M&uacute;sicas</a></div>
</body>