<body>
	<h2>Artistas mais populares</h2>
	<div class="cloud">
											<a class="cloud0" alt="Adalberto e Adriano - Letras,cifras e m&uacute;ica" title="Adalberto e Adriano - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/adalberto-adriano.html">Adalberto e Adriano</a>
											<a class="cloud0" alt="Altemar Dutra - Letras,cifras e m&uacute;ica" title="Altemar Dutra - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/altemar-dutra.html">Altemar Dutra</a>
													<a class="cloud4" alt="Beyonce Featuring Jay-Z - Letras,cifras e m&uacute;ica" title="Beyonce Featuring Jay-Z - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/beyonce-featuring-jay-z.html">Beyonce Featuring Jay-Z</a>
													<a class="cloud1" alt="Chico Science & Nação Zumbi - Letras,cifras e m&uacute;ica" title="Chico Science & Nação Zumbi - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/chico-science-nacao-zumbi.html">Chico Science & Nação Zumbi</a>
													<a class="cloud1" alt="Claudinho & Buchecha - Letras,cifras e m&uacute;ica" title="Claudinho & Buchecha - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/claudinho-buchecha.html">Claudinho & Buchecha</a>
													<a class="cloud1" alt="Cleiton e Huggo - Letras,cifras e m&uacute;ica" title="Cleiton e Huggo - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/cleiton-e-huggo.html">Cleiton e Huggo</a>
											<a class="cloud0" alt="Edson e Hudson - Letras,cifras e m&uacute;ica" title="Edson e Hudson - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/edson-e-hudson.html">Edson e Hudson</a>
													<a class="cloud2" alt="Exalta Samba - Letras,cifras e m&uacute;ica" title="Exalta Samba - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/exalta-samba.html">Exalta Samba</a>
													<a class="cloud4" alt="Exaltasamba - Letras,cifras e m&uacute;ica" title="Exaltasamba - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/exaltasamba.html">Exaltasamba</a>
													<a class="cloud4" alt="Fernando e Sorocaba - Letras,cifras e m&uacute;ica" title="Fernando e Sorocaba - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/fernando-e-sorocaba.html">Fernando e Sorocaba</a>
													<a class="cloud3" alt="Grupo Revelação - Letras,cifras e m&uacute;ica" title="Grupo Revelação - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/grupo-revelacao.html">Grupo Revelação</a>
													<a class="cloud2" alt="Jorge Vercilo - Letras,cifras e m&uacute;ica" title="Jorge Vercilo - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/jorge-vercilo.html">Jorge Vercilo</a>
													<a class="cloud4" alt="Jorge e Mateus - Letras,cifras e m&uacute;ica" title="Jorge e Mateus - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/jorge-e-mateus.html">Jorge e Mateus</a>
													<a class="cloud3" alt="João Bosco e Vinicius - Letras,cifras e m&uacute;ica" title="João Bosco e Vinicius - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/joao-bosco-e-vinicius.html">João Bosco e Vinicius</a>
													<a class="cloud3" alt="João Carreiro E Capataz - Letras,cifras e m&uacute;ica" title="João Carreiro E Capataz - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/joao-carreiro-e-capataz.html">João Carreiro E Capataz</a>
													<a class="cloud4" alt="Ke$ha - Letras,cifras e m&uacute;ica" title="Ke$ha - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/ke$ha.html">Ke$ha</a>
													<a class="cloud1" alt="Los Hermanos - Letras,cifras e m&uacute;ica" title="Los Hermanos - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/los-hermanos.html">Los Hermanos</a>
													<a class="cloud2" alt="Maria Cecília e Rodolfo - Letras,cifras e m&uacute;ica" title="Maria Cecília e Rodolfo - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/maria-cecilia-e-rodolfo.html">Maria Cecília e Rodolfo</a>
											<a class="cloud0" alt="Ministério Atos de Adoração - Letras,cifras e m&uacute;ica" title="Ministério Atos de Adoração - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/ministerio-atos-de-adoracao.html">Ministério Atos de Adoração</a>
													<a class="cloud3" alt="Nx Zero - Letras,cifras e m&uacute;ica" title="Nx Zero - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/nxzero.html">Nx Zero</a>
													<a class="cloud2" alt="Padre Fabio De Melo - Letras,cifras e m&uacute;ica" title="Padre Fabio De Melo - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/padre-fabio-de-melo.html">Padre Fabio De Melo</a>
											<a class="cloud0" alt="Ricardo e João Fernando - Letras,cifras e m&uacute;ica" title="Ricardo e João Fernando - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/ricardo-e-joao-fernando.html">Ricardo e João Fernando</a>
													<a class="cloud3" alt="Rosa De Saron - Letras,cifras e m&uacute;ica" title="Rosa De Saron - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/rosa-de-saron.html">Rosa De Saron</a>
													<a class="cloud1" alt="Sara Brightman - Letras,cifras e m&uacute;ica" title="Sara Brightman - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/sara-brightman.html">Sara Brightman</a>
													<a class="cloud2" alt="Zé Henrique E Gabriel - Letras,cifras e m&uacute;ica" title="Zé Henrique E Gabriel - Letras,cifras e m&uacute;sica" rel="tag" href="/artista/ze-henrique-e-gabriel.html">Zé Henrique E Gabriel</a>
		</div>
	<div class="footer"><a href="/top/artistas.html" title="TOP 100 Artistas Mais Acessados">TOP 100 Artistas</a></div>
</body>