<div id="twtr-widget-1" class="twtr-widget twtr-scroll">
  <div style="width: 625px;" class="twtr-doc">
    <div class="twtr-hd">
      <h3>Sobre o Tocaletra no</h3>
      <h4>Twitter</h4>
    </div>
    <div class="twtr-bd">
      <div style="height: 260px;" class="twtr-timeline">
        <div class="twtr-tweets">
          <div class="twtr-reference-tweet"></div>
          <div id="tweet-id-54" class="twtr-tweet"
          style="opacity: 1; height: 52px;">
            <div class="twtr-tweet-wrap">
              <div class="twtr-avatar">
                <div class="twtr-img">
                  <a href="http://twitter.com/apaulinhasp"
                  target="_blank">
                    <img src="http://static.twitter.com/images/default_profile_normal.png"
                    alt="apaulinhasp profile">
                      <div class="twtr-tweet-text">
                        <p>
                        <a class="twtr-user"
                        href="http://twitter.com/apaulinhasp"
                        target="_blank">apaulinhasp</a>Divino
                        Maravilhoso de Gal Costa- vibe de hoje- 
                        <a href="http://t.co/sqxVioU"
                        target="_blank" class="twtr-hyperlink">
                        http://t.co/sqxVioU</a>
                        <em>
                        <a href="http://twitter.com/apaulinhasp/status/51442738750689280"
                        time="Sat, 26 Mar 2011 00:37:59 +0000"
                        class="twtr-timestamp" target="_blank">4
                        days ago</a>&#183; 
                        <a href="http://twitter.com/?status=@apaulinhasp%20&amp;in_reply_to_status_id=51442738750689280&amp;in_reply_to=apaulinhasp"
                        class="twtr-reply" target="_blank">
                        reply</a></em></p>
                      </div>

                    </img>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
