package br.com.tamandua.persistence;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Annotation generated by hbm2java
 */
@Entity
@Table(name = "annotation")
public class Annotation implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Long idAnnotation;
    private EntityDescriptor entityDescriptor;
    private User user;
    private long idEntity;
    private String text;
    private Integer musicMeter;
    private String type;

    public Annotation() {
    }

    public Annotation(EntityDescriptor entityDescriptor, User user, long idEntity, String text) {
        this.entityDescriptor = entityDescriptor;
        this.user = user;
        this.idEntity = idEntity;
        this.text = text;
    }

    public Annotation(EntityDescriptor entityDescriptor, User user, long idEntity, String text, Integer musicMeter, String type) {
        this.entityDescriptor = entityDescriptor;
        this.user = user;
        this.idEntity = idEntity;
        this.text = text;
        this.musicMeter = musicMeter;
        this.type = type;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_annotation", unique = true, nullable = false)
    public Long getIdAnnotation() {
        return this.idAnnotation;
    }

    public void setIdAnnotation(Long idAnnotation) {
        this.idAnnotation = idAnnotation;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entity_descriptor", nullable = false)
    public EntityDescriptor getEntityDescriptor() {
        return this.entityDescriptor;
    }

    public void setEntityDescriptor(EntityDescriptor entityDescriptor) {
        this.entityDescriptor = entityDescriptor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "id_entity", nullable = false)
    public long getIdEntity() {
        return this.idEntity;
    }

    public void setIdEntity(long idEntity) {
        this.idEntity = idEntity;
    }

    @Column(name = "text", nullable = false, length = 1000)
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Column(name = "music_meter")
    public Integer getMusicMeter() {
        return this.musicMeter;
    }

    public void setMusicMeter(Integer musicMeter) {
        this.musicMeter = musicMeter;
    }

    @Column(name = "type", length = 9)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
