package br.com.tamandua.persistence;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArtistAlias generated by hbm2java
 */
@Entity
@Table(name = "artist_alias")
public class ArtistAlias implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Long idArtistAlias;
    private Artist artist;
    private String artistAlias;

    public ArtistAlias() {
    }

    public ArtistAlias(Artist artist, String artistAlias) {
        this.artist = artist;
        this.artistAlias = artistAlias;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_artist_alias", unique = true, nullable = false)
    public Long getIdArtistAlias() {
        return this.idArtistAlias;
    }

    public void setIdArtistAlias(Long idArtistAlias) {
        this.idArtistAlias = idArtistAlias;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_artist", nullable = false)
    public Artist getArtist() {
        return this.artist;
    }

    public void setArtist(Artist artist) {
        this.artist = artist;
    }

    @Column(name = "artist_alias", nullable = false, length = 100)
    public String getArtistAlias() {
        return this.artistAlias;
    }

    public void setArtistAlias(String artistAlias) {
        this.artistAlias = artistAlias;
    }

}
