package br.com.tamandua.persistence;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Moderation generated by hbm2java
 */
@Entity
@Table(name = "moderation")
public class Moderation implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Long idModeration;
    private EntityDescriptor entityDescriptor;
    private User user;
    private Date moderationDate;
    private Long idEntity;
    private String status;
    private String oldValue;
    private String newValue;
    private String affectedFieldName;

    public Moderation() {
    }

    public Moderation(EntityDescriptor entityDescriptor, User user, Date moderationDate, Long idEntity, String status,
            String oldValue, String newValue, String affectedFieldName) {
        this.entityDescriptor = entityDescriptor;
        this.user = user;
        this.moderationDate = moderationDate;
        this.idEntity = idEntity;
        this.status = status;
        this.oldValue = oldValue;
        this.newValue = newValue;
        this.affectedFieldName = affectedFieldName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_moderation", unique = true, nullable = false)
    public Long getIdModeration() {
        return this.idModeration;
    }

    public void setIdModeration(Long idModeration) {
        this.idModeration = idModeration;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entity_descriptor")
    public EntityDescriptor getEntityDescriptor() {
        return this.entityDescriptor;
    }

    public void setEntityDescriptor(EntityDescriptor entityDescriptor) {
        this.entityDescriptor = entityDescriptor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "moderation_date", length = 10)
    public Date getModerationDate() {
        return this.moderationDate;
    }

    public void setModerationDate(Date moderationDate) {
        this.moderationDate = moderationDate;
    }

    @Column(name = "id_entity")
    public Long getIdEntity() {
        return this.idEntity;
    }

    public void setIdEntity(Long idEntity) {
        this.idEntity = idEntity;
    }

    @Column(name = "status", length = 8)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "old_value")
    public String getOldValue() {
        return this.oldValue;
    }

    public void setOldValue(String oldValue) {
        this.oldValue = oldValue;
    }

    @Column(name = "new_value")
    public String getNewValue() {
        return this.newValue;
    }

    public void setNewValue(String newValue) {
        this.newValue = newValue;
    }

    @Column(name = "affected_field_name", length = 100)
    public String getAffectedFieldName() {
        return this.affectedFieldName;
    }

    public void setAffectedFieldName(String affectedFieldName) {
        this.affectedFieldName = affectedFieldName;
    }

}
