package br.com.tamandua.persistence;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MusicArtist generated by hbm2java
 */
@Entity
@Table(name = "music_artist")
public class MusicArtist implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    
    private MusicArtistId id;
    private Music music;
    private Artist artist;
    private String participation;

    public MusicArtist() {
    }

    public MusicArtist(MusicArtistId id, Music music, Artist artist) {
        this.id = id;
        this.music = music;
        this.artist = artist;
    }

    @EmbeddedId
    @AttributeOverrides( { @AttributeOverride(name = "idMusic", column = @Column(name = "id_music", nullable = false)),
            @AttributeOverride(name = "idArtist", column = @Column(name = "id_artist", nullable = false)),
            @AttributeOverride(name = "participation", column = @Column(name = "participation", length = 11)) })
    public MusicArtistId getId() {
        return this.id;
    }

    public void setId(MusicArtistId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_music", nullable = false, insertable = false, updatable = false)
    public Music getMusic() {
        return this.music;
    }

    public void setMusic(Music music) {
        this.music = music;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_artist", nullable = false, insertable = false, updatable = false)
    public Artist getArtist() {
        return this.artist;
    }

    public void setArtist(Artist artist) {
        this.artist = artist;
    }

    @Column(name = "participation")
	public String getParticipation() {
		return participation;
	}

	public void setParticipation(String participation) {
		this.participation = participation;
	}

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        MusicArtist other = (MusicArtist) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "MusicArtist [" + (artist != null ? "artist=" + artist + ", " : "") + (id != null ? "id=" + id + ", " : "")
                + (music != null ? "music=" + music + ", " : "") + (participation != null ? "participation=" + participation : "") + "]";
    }

}
