<meta name="title" content="Listagem dos TOP 100 artistas" />
<meta name="description" content="Listagem dos TOP 100 artistas - no TocaLetra você encontra mais de 2 milhões de Letras de Música. Também encontra Cifras, Vídeos, Imagens e ouve as músicas de seus artistas preferidos." />
<title>Listagem dos TOP 100 artistas</title>
<link rel="canonical" href="http://www.tocaletra.com.br/top/artistas.html" />
<!-- X -->
<div id="breadcrumbs">
	<a href="http://tocaletra.uol.com.br" title="TocaLetra.com.br">TocaLetra</a> »
	<strong>TOP 100 Artistas</a></strong>
</div>

<div id="info-artistas">
	<div id="dados-letra">
	    <p id="nome-musica">TOP 100 Artistas</p>
	    <p id="nome-artista">Mais Acessados</p>
	</div>		
	<div id="share-panel-no-gallery">
		<a id="orkut-button" class="share-button" title="Orkut" href="javascript: void(0)"
			onclick="shareOrkut('http://www.tocaletra.com.br/top/artistas.html')"></a>
		<a id="twitter-button" class="share-button" title="Twitter" href="javascript: void(0)"
			onclick="shareTwitter('http://www.tocaletra.com.br/top/artistas.html', 'Listagem das TOP 100 artistas no @tocaletra.')"></a>
		<fb:like href="http://www.tocaletra.com.br/top/artistas.html" layout="button_count" show_faces="false" width="300"></fb:like>
	</div>
</div>

<div class="banner">
	<script type="text/javascript">		
		descrColor="000000"; titleColor="CC0000"; urlColor="000066"; borderColor="000033"; bgColor="FFFFFF"; altColor="FFFFFF";
		coddisplaysupplier="adb29daaacbd47a6bc92f3f2d86af736"; formatId="2"; deslabel="pag-letra"; numads="2"; type="1";
	</script>
	<script type="text/javascript" src="http://adrequisitor-af.lp.uol.com.br/uolaf.js"></script>
</div>

<div id="listagem">
							
   <div class="coluna">
       <ol>
		   		   	    					<li><a title="Fernando e Sorocaba - Letras, cifras e música" href="/artista/fernando-e-sorocaba.html">Fernando e Sorocaba</a></li>		
						   		   	    					<li><a title="Jorge e Mateus - Letras, cifras e música" href="/artista/jorge-e-mateus.html">Jorge e Mateus</a></li>		
						   		   	    					<li><a title="Ke$ha - Letras, cifras e música" href="/artista/ke$ha.html">Ke$ha</a></li>		
						   		   	    					<li><a title="Exaltasamba - Letras, cifras e música" href="/artista/exaltasamba.html">Exaltasamba</a></li>		
						   		   	    					<li><a title="Beyonce Featuring Jay-Z - Letras, cifras e música" href="/artista/beyonce-featuring-jay-z.html">Beyonce Featuring Jay-Z</a></li>		
						   		   	    					<li><a title="Nx Zero - Letras, cifras e música" href="/artista/nxzero.html">Nx Zero</a></li>		
						   		   	    					<li><a title="Grupo Revelação - Letras, cifras e música" href="/artista/grupo-revelacao.html">Grupo Revelação</a></li>		
						   		   	    					<li><a title="Rosa De Saron - Letras, cifras e música" href="/artista/rosa-de-saron.html">Rosa De Saron</a></li>		
						   		   	    					<li><a title="João Carreiro E Capataz - Letras, cifras e música" href="/artista/joao-carreiro-e-capataz.html">João Carreiro E Capataz</a></li>		
						   		   	    					<li><a title="João Bosco e Vinicius - Letras, cifras e música" href="/artista/joao-bosco-e-vinicius.html">João Bosco e Vinicius</a></li>		
						   		   	    					</ol>
					</div>
					<div class="coluna">
					<ol start="11">    	
		   	    					<li><a title="Padre Fabio De Melo - Letras, cifras e música" href="/artista/padre-fabio-de-melo.html">Padre Fabio De Melo</a></li>		
						   		   	    					<li><a title="Zé Henrique E Gabriel - Letras, cifras e música" href="/artista/ze-henrique-e-gabriel.html">Zé Henrique E Gabriel</a></li>		
						   		   	    					<li><a title="Jorge Vercilo - Letras, cifras e música" href="/artista/jorge-vercilo.html">Jorge Vercilo</a></li>		
						   		   	    					<li><a title="Maria Cecília e Rodolfo - Letras, cifras e música" href="/artista/maria-cecilia-e-rodolfo.html">Maria Cecília e Rodolfo</a></li>		
						   		   	    					<li><a title="Exalta Samba - Letras, cifras e música" href="/artista/exalta-samba.html">Exalta Samba</a></li>		
						   		   	    					<li><a title="Cleiton e Huggo - Letras, cifras e música" href="/artista/cleiton-e-huggo.html">Cleiton e Huggo</a></li>		
						   		   	    					<li><a title="Chico Science & Nação Zumbi - Letras, cifras e música" href="/artista/chico-science-nacao-zumbi.html">Chico Science & Nação Zumbi</a></li>		
						   		   	    					<li><a title="Sara Brightman - Letras, cifras e música" href="/artista/sara-brightman.html">Sara Brightman</a></li>		
						   		   	    					<li><a title="Los Hermanos - Letras, cifras e música" href="/artista/los-hermanos.html">Los Hermanos</a></li>		
						   		   	    					<li><a title="Claudinho & Buchecha - Letras, cifras e música" href="/artista/claudinho-buchecha.html">Claudinho & Buchecha</a></li>		
						   		   	    					</ol>
					</div>
					<div class="coluna">
					<ol start="21">    	
		   	    					<li><a title="Adalberto e Adriano - Letras, cifras e música" href="/artista/adalberto-adriano.html">Adalberto e Adriano</a></li>		
						   		   	    					<li><a title="Edson e Hudson - Letras, cifras e música" href="/artista/edson-e-hudson.html">Edson e Hudson</a></li>		
						   		   	    					<li><a title="Ministério Atos de Adoração - Letras, cifras e música" href="/artista/ministerio-atos-de-adoracao.html">Ministério Atos de Adoração</a></li>		
						   		   	    					<li><a title="Ricardo e João Fernando - Letras, cifras e música" href="/artista/ricardo-e-joao-fernando.html">Ricardo e João Fernando</a></li>		
						   		   	    					<li><a title="Altemar Dutra - Letras, cifras e música" href="/artista/altemar-dutra.html">Altemar Dutra</a></li>		
						   		   	    					<li><a title="Uriel Lozano - Letras, cifras e música" href="/artista/uriel-lozano.html">Uriel Lozano</a></li>		
						   		   	    					<li><a title="Adriana Calcanhotto - Letras, cifras e música" href="/artista/adriana-calcanhoto.html">Adriana Calcanhotto</a></li>		
						   		   	    					<li><a title="Os Paralamas do Sucesso - Letras, cifras e música" href="/artista/paralamas-do-sucesso.html">Os Paralamas do Sucesso</a></li>		
						   	   </ol>
   </div>
</div>

<div class="banner">
	<script type="text/javascript">		
		descrColor="000000"; titleColor="CC0000"; urlColor="000066"; borderColor="000033"; bgColor="FFFFFF"; altColor="FFFFFF";
		coddisplaysupplier="adb29daaacbd47a6bc92f3f2d86af736"; formatId="2"; deslabel="pag-letra"; numads="2"; type="1";
	</script>
	<script type="text/javascript" src="http://adrequisitor-af.lp.uol.com.br/uolaf.js"></script>
</div>
