<meta name="title" content="Listagem das TOP 100 músicas" />
<meta name="description" content="Listagem das TOP 100 músicas - no TocaLetra você encontra mais de 2 milhões de Letras de Música. Também encontra Cifras, Vídeos, Imagens e ouve as músicas de seus artistas preferidos." />
<title>Listagem das TOP 100 músicas</title>
<link rel="canonical" href="http://www.tocaletra.com.br/top/musicas.html" />
<!-- X -->
<div id="breadcrumbs">
	<a href="http://tocaletra.uol.com.br" title="TocaLetra.com.br">TocaLetra</a> »
	<strong>TOP 100 Músicas</strong>
</div>

<div id="info-artistas">
    <div id="dados-letra">
	    <p id="nome-musica">TOP 100 Músicas</p>
	    <p id="nome-artista">Mais Acessadas</p>
	</div>		
	<div id="share-panel-no-gallery">
		<a id="orkut-button" class="share-button" title="Orkut" href="javascript: void(0)"
			onclick="shareOrkut('http://www.tocaletra.com.br/top/musicas.html')"></a>
		<a id="twitter-button" class="share-button" title="Twitter" href="javascript: void(0)"
			onclick="shareTwitter('http://www.tocaletra.com.br/top/musicas.html', 'Listagem das TOP 100 músicas no @tocaletra.')"></a>
		<fb:like href="http://www.tocaletra.com.br/top/musicas.html" layout="button_count" show_faces="false" width="300"></fb:like>
	</div>
</div>

<div class="banner">
	<script type="text/javascript">		
		descrColor="000000"; titleColor="CC0000"; urlColor="000066"; borderColor="000033"; bgColor="FFFFFF"; altColor="FFFFFF";
		coddisplaysupplier="adb29daaacbd47a6bc92f3f2d86af736"; formatId="2"; deslabel="pag-letra"; numads="2"; type="1";
	</script>
	<script type="text/javascript" src="http://adrequisitor-af.lp.uol.com.br/uolaf.js"></script>
</div>

<div id="listagem">
							
   <div class="coluna">
       <ol>
		   		   	    					<li><a title="Passaro De Fogo - Letras, cifras e música" href="/musica/paula-fernandes/passaro-de-fogo.html">Paula Fernandes - Passaro De Fogo</a></li>		
						   		   	    					<li><a title="Madri - Letras, cifras e música" href="/musica/fernando-e-sorocaba/madri.html">Fernando e Sorocaba - Madri</a></li>		
						   		   	    					<li><a title="Your Love Is My Drug - Letras, cifras e música" href="/musica/ke$ha/your-love-is-my-drug.html">Ke$ha - Your Love Is My Drug</a></li>		
						   		   	    					<li><a title="Stereo Love (feat Maya) - Letras, cifras e música" href="/musica/edward-maya/stereo-love-feat-maya.html">Edward Maya - Stereo Love (feat Maya)</a></li>		
						   		   	    					<li><a title="Hey, Soul Sister - Letras, cifras e música" href="/musica/train/hey-soul-sister.html">Train - Hey, Soul Sister</a></li>		
						   		   	    					<li><a title="Chuva Chover - Letras, cifras e música" href="/musica/paula-fernandes/chuva-chover.html">Paula Fernandes - Chuva Chover</a></li>		
						   		   	    					<li><a title="Quero Sim - Letras, cifras e música" href="/musica/paula-fernandes/quero-sim.html">Paula Fernandes - Quero Sim</a></li>		
						   		   	    					<li><a title="Meu Eu Em Você - Letras, cifras e música" href="/musica/paula-fernandes/meu-eu-em-voce.html">Paula Fernandes - Meu Eu Em Você</a></li>		
						   		   	    					<li><a title="Meteoro - Letras, cifras e música" href="/musica/luan-santana/meteoro.html">Luan Santana - Meteoro</a></li>		
						   		   	    					<li><a title="Baby - Letras, cifras e música" href="/musica/justin-bieber/baby.html">Justin Bieber - Baby</a></li>		
						   		   	    					<li><a title="Sem Você - Letras, cifras e música" href="/musica/paula-fernandes/sem-voce.html">Paula Fernandes - Sem Você</a></li>		
						   		   	    					<li><a title="E Daí - Letras, cifras e música" href="/musica/guilherme-e-santiago/e-dai.html">Guilherme & Santiago - E Daí</a></li>		
						   		   	    					<li><a title="Bad Romance - Letras, cifras e música" href="/musica/lady-gaga/bad-romance.html">Lady Gaga - Bad Romance</a></li>		
						   		   	    					<li><a title="Borboletas - Letras, cifras e música" href="/musica/victor-leo/borboletas.html">Victor e Leo - Borboletas</a></li>		
						   		   	    					<li><a title="A Carta - Letras, cifras e música" href="/musica/eduardo-costa/a-carta.html">Eduardo Costa - A Carta</a></li>		
						   		   	    					<li><a title="Complicado Demais - Letras, cifras e música" href="/musica/paula-fernandes/complicado-demais.html">Paula Fernandes - Complicado Demais</a></li>		
						   		   	    					<li><a title="Pra Não Morrer De Amor - Letras, cifras e música" href="/musica/bruno-e-marrone/pra-nao-morrer-de-amor.html">Bruno e Marrone - Pra Não Morrer De Amor</a></li>		
						   		   	    					<li><a title="Tik Tok - Letras, cifras e música" href="/musica/ke$ha/tik-tok.html">Ke$ha - Tik Tok</a></li>		
						   		   	    					<li><a title="Alejandro - Letras, cifras e música" href="/musica/lady-gaga/alejandro.html">Lady Gaga - Alejandro</a></li>		
						   		   	    					<li><a title="Chora,me liga - Letras, cifras e música" href="/musica/joao-bosco-e-vinicius/chorame-liga.html">João Bosco e Vinícius - Chora,me liga</a></li>		
						   		   	    					<li><a title="A Mulher Que Eu Amo - Letras, cifras e música" href="/musica/roberto-carlos/a-mulher-que-eu-amo.html">Roberto Carlos - A Mulher Que Eu Amo</a></li>		
						   		   	    					<li><a title="Levo Comigo - Letras, cifras e música" href="/musica/restart/levo-comigo.html">Restart - Levo Comigo</a></li>		
						   		   	    					<li><a title="Jeito De Mato - Letras, cifras e música" href="/musica/paula-fernandes/jeito-de-mato.html">Paula Fernandes - Jeito De Mato</a></li>		
						   		   	    					<li><a title="Bala De Prata - Letras, cifras e música" href="/musica/fernando-e-sorocaba/bala-de-prata.html">Fernando e Sorocaba - Bala De Prata</a></li>		
						   		   	    					<li><a title="Gypsy - Letras, cifras e música" href="/musica/shakira/gipsy.html">Shakira - Gypsy</a></li>		
						   		   	    					<li><a title="Sede De Amor - Letras, cifras e música" href="/musica/paula-fernandes/sede-de-amor.html">Paula Fernandes - Sede De Amor</a></li>		
						   		   	    					<li><a title="Quem Foi que Disse? - Letras, cifras e música" href="/musica/eduardo-costa/quem-foi-que-disse.html">Eduardo Costa - Quem Foi que Disse?</a></li>		
						   		   	    					<li><a title="Só Agora - Letras, cifras e música" href="/musica/pitty/so-agora.html">Pitty - Só Agora</a></li>		
						   		   	    					<li><a title="Futuro Prometido - Letras, cifras e música" href="/musica/sorriso-maroto/futuro-prometido.html">Sorriso Maroto - Futuro Prometido</a></li>		
						   		   	    					<li><a title="Estrela Cadente - Letras, cifras e música" href="/musica/victor-leo/estrela-cadente.html">Victor e Leo - Estrela Cadente</a></li>		
						   		   	    					<li><a title="Halo - Letras, cifras e música" href="/musica/beyonce-featuring-jay-z/halo.html">Beyonce Featuring Jay-Z - Halo</a></li>		
						   		   	    					<li><a title="Pra Que Inventaram O Amor? - Letras, cifras e música" href="/musica/paula-fernandes/pra-que-inventaram-o-amor.html">Paula Fernandes - Pra Que Inventaram O Amor?</a></li>		
						   		   	    					<li><a title="Sempre Com Você - Letras, cifras e música" href="/musica/luan-santana/sempre-com-voce.html">Luan Santana - Sempre Com Você</a></li>		
						   		   	    					<li><a title="Sinais - Letras, cifras e música" href="/musica/sorriso-maroto/sinais.html">Sorriso Maroto - Sinais</a></li>		
						   		   	    					</ol>
					</div>
					<div class="coluna">
					<ol start="35">    	
		   	    					<li><a title="Só Os Loucos Sabem - Letras, cifras e música" href="/musica/charlie-brown-jr/so-os-loucos-sabem.html">Charlie Brown Jr. - Só Os Loucos Sabem</a></li>		
						   		   	    					<li><a title="Anunciação - Letras, cifras e música" href="/musica/alceu-valenca/anunciacao.html">Alceu Valença - Anunciação</a></li>		
						   		   	    					<li><a title="Ao Vivo E Em Cores - Letras, cifras e música" href="/musica/victor-leo/ao-vivo-e-em-cores.html">Victor e Leo - Ao Vivo E Em Cores</a></li>		
						   		   	    					<li><a title="One In a Million - Letras, cifras e música" href="/musica/miley-cyrus/one-in-a-million.html">Miley Cyrus - One In a Million</a></li>		
						   		   	    					<li><a title="Gamei - Letras, cifras e música" href="/musica/exaltasamba/gamei.html">Exaltasamba - Gamei</a></li>		
						   		   	    					<li><a title="Paga Pau - Letras, cifras e música" href="/musica/fernando-e-sorocaba/paga-pau.html">Fernando e Sorocaba - Paga Pau</a></li>		
						   		   	    					<li><a title="Cheiro de Relva - Letras, cifras e música" href="/musica/paula-fernandes/cheiro-de-relva.html">Paula Fernandes - Cheiro de Relva</a></li>		
						   		   	    					<li><a title="Anjos De Resgate - Letras, cifras e música" href="/musica/padre-marcelo-rossi/anjos-de-resgate.html">Padre Marcelo Rossi - Anjos De Resgate</a></li>		
						   		   	    					<li><a title="Pula-Pula - Letras, cifras e música" href="/musica/aline-barros-e-cia/pula-pula.html">Aline Barros e Cia. - Pula-Pula</a></li>		
						   		   	    					<li><a title="Tô De Cara - Letras, cifras e música" href="/musica/luan-santana/to-de-cara.html">Luan Santana - Tô De Cara</a></li>		
						   		   	    					<li><a title="Tem Que Ser Você - Letras, cifras e música" href="/musica/victor-leo/tem-que-ser-voce.html">Victor e Leo - Tem Que Ser Você</a></li>		
						   		   	    					<li><a title="Meet Me Halfway - Letras, cifras e música" href="/musica/black-eyed-peas/meet-me-halfway.html">Black Eyed Peas - Meet Me Halfway</a></li>		
						   		   	    					<li><a title="Sacanagem Tua - Letras, cifras e música" href="/musica/janaynna-targino/sacanagem-tua.html">Janaynna Targino - Sacanagem Tua</a></li>		
						   		   	    					<li><a title="Voa Beija Flor - Letras, cifras e música" href="/musica/jorge-e-mateus/voa-beija-flor.html">Jorge e Mateus - Voa Beija Flor</a></li>		
						   		   	    					<li><a title="Meu Mestre - Letras, cifras e música" href="/musica/lazaro/meu-mestre.html">Lázaro - Meu Mestre</a></li>		
						   		   	    					<li><a title="Ta Escrito - Letras, cifras e música" href="/musica/grupo-revelacao/ta-escrito.html">Grupo Revelação - Ta Escrito</a></li>		
						   		   	    					<li><a title="Valeu - Letras, cifras e música" href="/musica/exaltasamba/valeu.html">Exaltasamba - Valeu</a></li>		
						   		   	    					<li><a title="Paparazzi - Letras, cifras e música" href="/musica/lady-gaga/paparazzi.html">Lady Gaga - Paparazzi</a></li>		
						   		   	    					<li><a title="Amado - Letras, cifras e música" href="/musica/vanessa-da-mata/amado.html">Vanessa da Mata - Amado</a></li>		
						   		   	    					<li><a title="Deus e Eu no Sertão - Letras, cifras e música" href="/musica/victor-leo/deus-e-eu-no-sertao.html">Victor e Leo - Deus e Eu no Sertão</a></li>		
						   		   	    					<li><a title="Velas E Vento - Letras, cifras e música" href="/musica/ana-carolina/velas-e-vento.html">Ana Carolina - Velas E Vento</a></li>		
						   		   	    					<li><a title="Fada - Letras, cifras e música" href="/musica/victor-leo/fada.html">Victor e Leo - Fada</a></li>		
						   		   	    					<li><a title="Ego - Letras, cifras e música" href="/musica/beyonce/ego.html">Beyoncé - Ego</a></li>		
						   		   	    					<li><a title="If I Were a Boy - Letras, cifras e música" href="/musica/beyonce-featuring-jay-z/if-i-were-a-boy.html">Beyonce Featuring Jay-Z - If I Were a Boy</a></li>		
						   		   	    					<li><a title="Jogo Do Amor - Letras, cifras e música" href="/musica/luan-santana/jogo-do-amor.html">Luan Santana - Jogo Do Amor</a></li>		
						   		   	    					<li><a title="Só Rezo - Letras, cifras e música" href="/musica/nxzero/so-rezo.html">Nx Zero - Só Rezo</a></li>		
						   		   	    					<li><a title="Fui - Letras, cifras e música" href="/musica/exaltasamba/fui.html">Exaltasamba - Fui</a></li>		
						   		   	    					<li><a title="Rude Boy - Letras, cifras e música" href="/musica/rihanna/rude-boy.html">Rihanna - Rude Boy</a></li>		
						   		   	    					<li><a title="Estoy Aquí - Letras, cifras e música" href="/musica/shakira/estoy-aqui.html">Shakira - Estoy Aquí</a></li>		
						   		   	    					<li><a title="Vai - Letras, cifras e música" href="/musica/paula-fernandes/vai.html">Paula Fernandes - Vai</a></li>		
						   		   	    					<li><a title="Russian Roulette - Letras, cifras e música" href="/musica/rihanna/russian-roulette.html">Rihanna - Russian Roulette</a></li>		
						   		   	    					<li><a title="Rehab - Letras, cifras e música" href="/musica/amy-winehouse/rehab.html">Amy Winehouse - Rehab</a></li>		
						   		   	    					<li><a title="Querendo Te Amar - Letras, cifras e música" href="/musica/jorge-e-mateus/querendo-te-amar.html">Jorge e Mateus - Querendo Te Amar</a></li>		
						   		   	    					<li><a title="Dança Menina - Letras, cifras e música" href="/musica/paula-fernandes/danca-menina.html">Paula Fernandes - Dança Menina</a></li>		
						   		   	    					</ol>
					</div>
					<div class="coluna">
					<ol start="69">    	
		   	    					<li><a title="O Mundo E Tão Pequeno - Letras, cifras e música" href="/musica/jorge-e-mateus/o-mundo-e-tao-pequeno.html">Jorge e Mateus - O Mundo E Tão Pequeno</a></li>		
						   		   	    					<li><a title="Telephone (feat. Beyoncé) - Letras, cifras e música" href="/musica/lady-gaga/telephone-feat-beyonce.html">Lady Gaga - Telephone (feat. Beyoncé)</a></li>		
						   		   	    					<li><a title="Chocolate - Letras, cifras e música" href="/musica/luan-santana/chocolate.html">Luan Santana - Chocolate</a></li>		
						   		   	    					<li><a title="Eu E Meu Pai - Letras, cifras e música" href="/musica/zeze-di-camargo-e-luciano/eu-e-meu-pai.html">Zezé Di Camargo e Luciano - Eu E Meu Pai</a></li>		
						   		   	    					<li><a title="Maria (português) - Letras, cifras e música" href="/musica/a-novica-rebelde-trilha-sonora/maria-portugues.html">A Noviça Rebelde - Maria (português)</a></li>		
						   		   	    					<li><a title="Entreolhares - Letras, cifras e música" href="/musica/ana-carolina/entreolhares.html">Ana Carolina - Entreolhares</a></li>		
						   		   	    					<li><a title="Vem Ficar Do Meu Lado - Letras, cifras e música" href="/musica/fernando-e-sorocaba/vem-ficar-do-meu-lado.html">Fernando e Sorocaba - Vem Ficar Do Meu Lado</a></li>		
						   		   	    					<li><a title="Pra Você Guardei O Amor - Letras, cifras e música" href="/musica/nando-reis/pra-voce-guardei-o-amor.html">Nando Reis - Pra Você Guardei O Amor</a></li>		
						   		   	    					<li><a title="Faz Um Milagre Em Mim - Letras, cifras e música" href="/musica/regis-danese/faz-um-milagre-em-mim.html">Regis Danese - Faz Um Milagre Em Mim</a></li>		
						   		   	    					<li><a title="Recomeçar - Letras, cifras e música" href="/musica/restart/recomecar.html">Restart - Recomeçar</a></li>		
						   		   	    					<li><a title="Tititi - Letras, cifras e música" href="/musica/rita-lee/tititi.html">Rita Lee - Tititi</a></li>		
						   		   	    					<li><a title="Tropicana (Morena Tropicana) - Letras, cifras e música" href="/musica/alceu-valenca/tropicana-(morena-tropicana).html">Alceu Valença - Tropicana (Morena Tropicana)</a></li>		
						   		   	    					<li><a title="Nao Valeu Pra Voce - Letras, cifras e música" href="/musica/eduardo-costa/nao-valeu-pra-voce.html">Eduardo Costa - Nao Valeu Pra Voce</a></li>		
						   		   	    					<li><a title="Infinita Highway - Letras, cifras e música" href="/musica/engenheiros-do-hawaii/infinita-highway.html">Engenheiros do Hawaii - Infinita Highway</a></li>		
						   		   	    					<li><a title="Sinais - Letras, cifras e música" href="/musica/luan-santana/sinais.html">Luan Santana - Sinais</a></li>		
						   		   	    					<li><a title="Conquistando O Impossível - Letras, cifras e música" href="/musica/jamily/conquistando-o-impossivel.html">Jamily - Conquistando O Impossível</a></li>		
						   		   	    					<li><a title="Se Vira - Letras, cifras e música" href="/musica/maria-cecilia-e-rodolfo/se-vira.html">Maria Cecília e Rodolfo - Se Vira</a></li>		
						   		   	    					<li><a title="Rebolation - Letras, cifras e música" href="/musica/parangole/rebolation.html">Parangolé - Rebolation</a></li>		
						   		   	    					<li><a title="Que Bom Que Você Chegou - Letras, cifras e música" href="/musica/bruna-karla/que-bom-que-voce-chegou.html">Bruna Karla - Que Bom Que Você Chegou</a></li>		
						   		   	    					<li><a title="Perdoa - Letras, cifras e música" href="/musica/banda-nechivile/perdoa.html">Banda Nechivile - Perdoa</a></li>		
						   		   	    					<li><a title="Mistérios - Letras, cifras e música" href="/musica/jorge-e-mateus/misterios.html">Jorge e Mateus - Mistérios</a></li>		
						   		   	    					<li><a title="Vou Fazer Pirraça - Letras, cifras e música" href="/musica/jorge-e-mateus/vou-fazer-pirraca.html">Jorge e Mateus - Vou Fazer Pirraça</a></li>		
						   		   	    					<li><a title="Feito Tatuagem - Letras, cifras e música" href="/musica/eduardo-costa/feito-tatuagem.html">Eduardo Costa - Feito Tatuagem</a></li>		
						   		   	    					<li><a title="Wonderwall - Letras, cifras e música" href="/musica/oasis/wonderwall.html">Oasis - Wonderwall</a></li>		
						   		   	    					<li><a title="Sem Você - Letras, cifras e música" href="/musica/rosa-de-saron/sem-voce.html">Rosa De Saron - Sem Você</a></li>		
						   		   	    					<li><a title="Nada Normal - Letras, cifras e música" href="/musica/victor-leo/nada-normal.html">Victor e Leo - Nada Normal</a></li>		
						   		   	    					<li><a title="Noites Traiçoeiras - Letras, cifras e música" href="/musica/padre-marcelo-rossi/noites-traicoeiras.html">Padre Marcelo Rossi - Noites Traiçoeiras</a></li>		
						   		   	    					<li><a title="Dancing Queen - Letras, cifras e música" href="/musica/abba/dancing-queen.html">ABBA - Dancing Queen</a></li>		
						   		   	    					<li><a title="Eu Te Amo Tanto - Letras, cifras e música" href="/musica/lazaro/eu-te-amo-tanto.html">Lázaro - Eu Te Amo Tanto</a></li>		
						   		   	    					<li><a title="Aqui É O Seu Lugar - Letras, cifras e música" href="/musica/luan-santana/aqui-e-o-seu-lugar.html">Luan Santana - Aqui É O Seu Lugar</a></li>		
						   		   	    					<li><a title="I Want To Know What Love Is - Letras, cifras e música" href="/musica/mariah-carey/i-want-to-know-what-love-is.html">Mariah Carey - I Want To Know What Love Is</a></li>		
						   		   	    					<li><a title="Deus Vai Fazer - Letras, cifras e música" href="/musica/lazaro/deus-vai-fazer.html">Lázaro - Deus Vai Fazer</a></li>		
						   	   </ol>
   </div>
</div>

<div class="banner">
	<script type="text/javascript">		
		descrColor="000000"; titleColor="CC0000"; urlColor="000066"; borderColor="000033"; bgColor="FFFFFF"; altColor="FFFFFF";
		coddisplaysupplier="adb29daaacbd47a6bc92f3f2d86af736"; formatId="2"; deslabel="pag-letra"; numads="2"; type="1";
	</script>
	<script type="text/javascript" src="http://adrequisitor-af.lp.uol.com.br/uolaf.js"></script>
</div>
