package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * AlbumVO generated by hbm2java
 */
@XmlRootElement(name = "album")
public class AlbumVO implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Long idAlbum;
    private ArtistVO artist;
    private ImageVO imageByIdCover;
    private ImageVO imageByIdBackCover;
    private String name;
    private Integer year;
    private Long idCountry;
    private String uri;
    private String url;
    private Set<ArtistDiscographyVO> artistDiscographies = new HashSet<ArtistDiscographyVO>(0);

    public AlbumVO() {
    }

    public AlbumVO(ImageVO imageByIdCover, ImageVO imageByIdBackCover) {
        this.imageByIdCover = imageByIdCover;
        this.imageByIdBackCover = imageByIdBackCover;
    }

    public AlbumVO(ArtistVO artist, ImageVO imageByIdCover, ImageVO imageByIdBackCover, String name, Integer year, Long idCountry,
            String uri, String url, Set<ArtistDiscographyVO> artistDiscographies) {
        this.artist = artist;
        this.imageByIdCover = imageByIdCover;
        this.imageByIdBackCover = imageByIdBackCover;
        this.name = name;
        this.year = year;
        this.idCountry = idCountry;
        this.uri = uri;
        this.url = url;
        this.artistDiscographies = artistDiscographies;
    }

    public Long getIdAlbum() {
        return this.idAlbum;
    }

    public void setIdAlbum(Long idAlbum) {
        this.idAlbum = idAlbum;
    }

    public ArtistVO getArtist() {
        return this.artist;
    }

    public void setArtist(ArtistVO artist) {
        this.artist = artist;
    }

    public ImageVO getImageByIdCover() {
        return this.imageByIdCover;
    }

    public void setImageByIdCover(ImageVO imageByIdCover) {
        this.imageByIdCover = imageByIdCover;
    }

    public ImageVO getImageByIdBackCover() {
        return this.imageByIdBackCover;
    }

    public void setImageByIdBackCover(ImageVO imageByIdBackCover) {
        this.imageByIdBackCover = imageByIdBackCover;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Long getIdCountry() {
        return this.idCountry;
    }

    public void setIdCountry(Long idCountry) {
        this.idCountry = idCountry;
    }

    public String getUri() {
        return this.uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Set<ArtistDiscographyVO> getArtistDiscographies() {
        return this.artistDiscographies;
    }

    public void setArtistDiscographies(Set<ArtistDiscographyVO> artistDiscographies) {
        this.artistDiscographies = artistDiscographies;
    }

	@Override
	public String toString() {
		return "AlbumVO ["
				+ (artist != null ? "artist=" + artist + ", " : "")
				+ (artistDiscographies != null ? "artistDiscographies="
						+ artistDiscographies + ", " : "")
				+ (idAlbum != null ? "idAlbum=" + idAlbum + ", " : "")
				+ (idCountry != null ? "idCountry=" + idCountry + ", " : "")
				+ (imageByIdBackCover != null ? "imageByIdBackCover="
						+ imageByIdBackCover + ", " : "")
				+ (imageByIdCover != null ? "imageByIdCover=" + imageByIdCover
						+ ", " : "")
				+ (name != null ? "name=" + name + ", " : "")
				+ (uri != null ? "uri=" + uri + ", " : "")
				+ (url != null ? "url=" + url + ", " : "")
				+ (year != null ? "year=" + year : "") + "]";
	}


}
