package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import javax.xml.bind.annotation.XmlRootElement;

/**
 * AnnotationVO generated by hbm2java
 */
@XmlRootElement(name = "annotation")
public class AnnotationVO implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Long idAnnotation;
    private EntityDescriptorVO entityDescriptor;
    private UserVO user;
    private long idEntity;
    private String text;
    private Integer musicMeter;
    private String type;

    public AnnotationVO() {
    }

    public AnnotationVO(EntityDescriptorVO entityDescriptor, UserVO user, long idEntity, String text) {
        this.entityDescriptor = entityDescriptor;
        this.user = user;
        this.idEntity = idEntity;
        this.text = text;
    }

    public AnnotationVO(EntityDescriptorVO entityDescriptor, UserVO user, long idEntity, String text, Integer musicMeter, String type) {
        this.entityDescriptor = entityDescriptor;
        this.user = user;
        this.idEntity = idEntity;
        this.text = text;
        this.musicMeter = musicMeter;
        this.type = type;
    }

    public Long getIdAnnotation() {
        return this.idAnnotation;
    }

    public void setIdAnnotation(Long idAnnotation) {
        this.idAnnotation = idAnnotation;
    }

    public EntityDescriptorVO getEntityDescriptor() {
        return this.entityDescriptor;
    }

    public void setEntityDescriptor(EntityDescriptorVO entityDescriptor) {
        this.entityDescriptor = entityDescriptor;
    }

    public UserVO getUser() {
        return this.user;
    }

    public void setUser(UserVO user) {
        this.user = user;
    }

    public long getIdEntity() {
        return this.idEntity;
    }

    public void setIdEntity(long idEntity) {
        this.idEntity = idEntity;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getMusicMeter() {
        return this.musicMeter;
    }

    public void setMusicMeter(Integer musicMeter) {
        this.musicMeter = musicMeter;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
