package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * ArtistVO generated by hbm2java
 */
@XmlRootElement(name="artist")
public class ArtistVO implements java.io.Serializable {

	public static final String FLAG_MODERATE = "S";
    public static final String FLAG_NO_MODERATE = "N";
    public static final String FLAG_PUBLIC = "S";
    public static final String FLAG_NO_PUBLIC = "N";
    
    private static final long serialVersionUID = 1L;
    private Long idArtist;
    private ImageVO imageHuge;
    private ImageVO imageTiny;
    private ImageVO image;
    private Set<ImageVO> allImages = new HashSet<ImageVO>(0);
    private String name;
    private Date dtBirth;
    private Date dtEnd;
    private Integer type;
    private Long totalAccess;
    private Long idCountry;
    private String sortName;
    private String letters;
    private String uri;
    private String url;
    private String flag_moderate;
    private String flag_public;
    private byte[] file;
    
    public ArtistVO() {
    }

    public ArtistVO(ImageVO imageHuge, ImageVO imageTiny, ImageVO image) {
        this.imageHuge = imageHuge;
        this.imageTiny = imageTiny;
        this.image = image;
    }
    
    public ArtistVO(ImageVO imageByIdImageHuge, ImageVO imageByIdImageTiny, ImageVO imageByIdImage, String name, Date dtBirth,
            Date dtEnd, Integer type, Long totalAccess, Long idCountry, String sortName, String letters, String uri, String url, 
            String flag_moderate, String flag_public, Set<MusicVO> musics, Set<ArtistDiscographyVO> artistDiscographies, Set<AlbumVO> albums, Set<MusicArtistVO> musicArtistVOs,
            Set<ArtistAliasVO> artistAliases, byte[] file) {
        this.imageHuge = imageByIdImageHuge;
        this.imageTiny = imageByIdImageTiny;
        this.image = imageByIdImage;
        this.name = name;
        this.dtBirth = dtBirth;
        this.dtEnd = dtEnd;
        this.type = type;
        this.totalAccess = totalAccess;
        this.idCountry = idCountry;
        this.sortName = sortName;
        this.letters = letters;
        this.uri = uri;
        this.flag_moderate = flag_moderate;
        this.flag_public = flag_public;
        this.url = url;
        this.file = file;
    }

    public Long getIdArtist() {
        return this.idArtist;
    }

    public void setIdArtist(Long idArtist) {
        this.idArtist = idArtist;
    }

    public ImageVO getImageHuge() {
        return this.imageHuge;
    }

    public void setImageHuge(ImageVO imageByIdImageHuge) {
        this.imageHuge = imageByIdImageHuge;
    }

    public ImageVO getImageTiny() {
        return this.imageTiny;
    }

    public void setImageTiny(ImageVO imageByIdImageTiny) {
        this.imageTiny = imageByIdImageTiny;
    }

    public ImageVO getImage() {
        return this.image;
    }

    public void setImage(ImageVO imageByIdImage) {
        this.image = imageByIdImage;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getDtBirth() {
        return this.dtBirth;
    }

    public void setDtBirth(Date dtBirth) {
        this.dtBirth = dtBirth;
    }

    public Date getDtEnd() {
        return this.dtEnd;
    }

    public void setDtEnd(Date dtEnd) {
        this.dtEnd = dtEnd;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getTotalAccess() {
        return this.totalAccess;
    }

    public void setTotalAccess(Long totalAccess) {
        this.totalAccess = totalAccess;
    }

    public Long getIdCountry() {
        return this.idCountry;
    }

    public void setIdCountry(Long idCountry) {
        this.idCountry = idCountry;
    }

    public String getSortName() {
        return this.sortName;
    }

    public void setSortName(String sortName) {
        this.sortName = sortName;
    }

    public String getLetters() {
        return this.letters;
    }

    public void setLetters(String letters) {
        this.letters = letters;
    }

    public String getUri() {
        return this.uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getFlag_moderate() {
		return flag_moderate;
	}

	public void setFlag_moderate(String flagModerate) {
		flag_moderate = flagModerate;
	}

	public String getFlag_public() {
		return flag_public;
	}

	public void setFlag_public(String flagPublic) {
		flag_public = flagPublic;
	}

	/**
     * @return the allImages
     */
    public Set<ImageVO> getAllImages() {
        return allImages;
    }

    /**
     * @param allImages the allImages to set
     */
    public void setAllImages(Set<ImageVO> allImages) {
        this.allImages = allImages;
    }

     public void addImage(ImageVO imageVO) {
        this.allImages.add(imageVO);
    }

    public byte[] getFile() {
		return file;
	}

	public void setFile(byte[] file) {
		this.file = file;
	}

    @Override
	public String toString() {
		return "ArtistVO ["
				+ (dtBirth != null ? "dtBirth=" + dtBirth + ", " : "")
				+ (dtEnd != null ? "dtEnd=" + dtEnd + ", " : "")
				+ (idArtist != null ? "idArtist=" + idArtist + ", " : "")
				+ (idCountry != null ? "idCountry=" + idCountry + ", " : "")
				+ (image != null ? "imageByIdImage=" + image
						+ ", " : "")
				+ (imageHuge != null ? "imageByIdImageHuge="
						+ imageHuge + ", " : "")
				+ (imageTiny != null ? "imageByIdImageTiny="
						+ imageTiny + ", " : "")
				+ (letters != null ? "letters=" + letters + ", " : "")
				+ (name != null ? "name=" + name + ", " : "")
				+ (sortName != null ? "sortName=" + sortName + ", " : "")
				+ (totalAccess != null ? "totalAccess=" + totalAccess + ", "
						: "") + (type != null ? "type=" + type + ", " : "")
				+ (uri != null ? "uri=" + uri + ", " : "")
				+ (url != null ? "url=" + url : "") + "]";
	}
}
