package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import javax.xml.bind.annotation.XmlRootElement;

/**
 * ArtistAliasVO generated by hbm2java
 */
@XmlRootElement(name = "artist_alias")
public class ArtistAliasVO implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Long idArtistAlias;
    private ArtistVO artist;
    private String artistAlias;

    public ArtistAliasVO() {
    }

    public ArtistAliasVO(ArtistVO artist, String artistAlias) {
        this.artist = artist;
        this.artistAlias = artistAlias;
    }

    public Long getIdArtistAlias() {
        return this.idArtistAlias;
    }

    public void setIdArtistAlias(Long idArtistAlias) {
        this.idArtistAlias = idArtistAlias;
    }

    public ArtistVO getArtist() {
        return this.artist;
    }

    public void setArtist(ArtistVO artist) {
        this.artist = artist;
    }

    public String getArtistAlias() {
        return this.artistAlias;
    }

    public void setArtistAlias(String artistAlias) {
        this.artistAlias = artistAlias;
    }

}
