package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import javax.xml.bind.annotation.XmlRootElement;

/**
 * ArtistDiscographyIdVO generated by hbm2java
 */
@XmlRootElement
public class ArtistDiscographyIdVO implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private long idAlbum;
    private long idArtist;

    public ArtistDiscographyIdVO() {
    }

    public ArtistDiscographyIdVO(long idAlbum, long idArtist) {
        this.idAlbum = idAlbum;
        this.idArtist = idArtist;
    }

    public long getIdAlbum() {
        return this.idAlbum;
    }

    public void setIdAlbum(long idAlbum) {
        this.idAlbum = idAlbum;
    }

    public long getIdArtist() {
        return this.idArtist;
    }

    public void setIdArtist(long idArtist) {
        this.idArtist = idArtist;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ArtistDiscographyIdVO))
            return false;
        ArtistDiscographyIdVO castOther = (ArtistDiscographyIdVO) other;

        return (this.getIdAlbum() == castOther.getIdAlbum()) && (this.getIdArtist() == castOther.getIdArtist());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getIdAlbum();
        result = 37 * result + (int) this.getIdArtist();
        return result;
    }

}
