package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import javax.xml.bind.annotation.XmlRootElement;

/**
 * ArtistDiscographyVO generated by hbm2java
 */
@XmlRootElement(name="artistDiscography")
public class ArtistDiscographyVO implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private ArtistDiscographyIdVO id;
    private ArtistVO artist;
    private AlbumVO album;

    public ArtistDiscographyVO() {
    }

    public ArtistDiscographyVO(ArtistDiscographyIdVO id, ArtistVO artist, AlbumVO album) {
        this.id = id;
        this.artist = artist;
        this.album = album;
    }

    public ArtistDiscographyIdVO getId() {
        return this.id;
    }

    public void setId(ArtistDiscographyIdVO id) {
        this.id = id;
    }

    public ArtistVO getArtist() {
        return this.artist;
    }

    public void setArtist(ArtistVO artist) {
        this.artist = artist;
    }

    public AlbumVO getAlbum() {
        return this.album;
    }

    public void setAlbum(AlbumVO album) {
        this.album = album;
    }

}
