package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * EntityDescriptorVO generated by hbm2java
 */
@XmlRootElement(name = "entityDescriptor")
public class EntityDescriptorVO implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private long idEntityDescriptor;
    private String entityName;
    private String tableName;
    private Set<AnnotationVO> annotations = new HashSet<AnnotationVO>(0);
    private Set<MultimediaVO> multimedias = new HashSet<MultimediaVO>(0);
    private Set<TagVO> tags = new HashSet<TagVO>(0);
    private Set<ModerationVO> moderations = new HashSet<ModerationVO>(0);

    public EntityDescriptorVO() {
    }

    public EntityDescriptorVO(long idEntityDescriptor) {
        this.idEntityDescriptor = idEntityDescriptor;
    }

    public EntityDescriptorVO(long idEntityDescriptor, String entityName, String tableName, Set<AnnotationVO> annotations,
            Set<MultimediaVO> multimedias, Set<TagVO> tags, Set<ModerationVO> moderations) {
        this.idEntityDescriptor = idEntityDescriptor;
        this.entityName = entityName;
        this.tableName = tableName;
        this.annotations = annotations;
        this.multimedias = multimedias;
        this.tags = tags;
        this.moderations = moderations;
    }

    public long getIdEntityDescriptor() {
        return this.idEntityDescriptor;
    }

    public void setIdEntityDescriptor(long idEntityDescriptor) {
        this.idEntityDescriptor = idEntityDescriptor;
    }

    public String getEntityName() {
        return this.entityName;
    }

    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public Set<AnnotationVO> getAnnotations() {
        return this.annotations;
    }

    public void setAnnotations(Set<AnnotationVO> annotations) {
        this.annotations = annotations;
    }

    public Set<MultimediaVO> getMultimedias() {
        return this.multimedias;
    }

    public void setMultimedias(Set<MultimediaVO> multimedias) {
        this.multimedias = multimedias;
    }

    public Set<TagVO> getTags() {
        return this.tags;
    }

    public void setTags(Set<TagVO> tags) {
        this.tags = tags;
    }

    public Set<ModerationVO> getModerations() {
        return this.moderations;
    }

    public void setModerations(Set<ModerationVO> moderations) {
        this.moderations = moderations;
    }

}
