package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import javax.xml.bind.annotation.XmlRootElement;

/**
 * MultimediaVO generated by hbm2java
 */
@XmlRootElement(name = "multimedia")
public class MultimediaVO implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Long idMultimedia;
    private EntityDescriptorVO entityDescriptor;
    private UserVO user;
    private Long idEntity;
    private String mediaType;
    private String title;
    private String description;
    private String contactInformation;
    private String embedCode;
    private String uri;
    private String url;

    public MultimediaVO() {
    }

    public MultimediaVO(EntityDescriptorVO entityDescriptor, UserVO user, Long idEntity, String mediaType, String title,
            String description, String contactInformation, String embedCode, String uri, String url) {
        this.entityDescriptor = entityDescriptor;
        this.user = user;
        this.idEntity = idEntity;
        this.mediaType = mediaType;
        this.title = title;
        this.description = description;
        this.contactInformation = contactInformation;
        this.embedCode = embedCode;
        this.uri = uri;
        this.url = url;
    }

    public Long getIdMultimedia() {
        return this.idMultimedia;
    }

    public void setIdMultimedia(Long idMultimedia) {
        this.idMultimedia = idMultimedia;
    }

    public EntityDescriptorVO getEntityDescriptor() {
        return this.entityDescriptor;
    }

    public void setEntityDescriptor(EntityDescriptorVO entityDescriptor) {
        this.entityDescriptor = entityDescriptor;
    }

    public UserVO getUser() {
        return this.user;
    }

    public void setUser(UserVO user) {
        this.user = user;
    }

    public Long getIdEntity() {
        return this.idEntity;
    }

    public void setIdEntity(Long idEntity) {
        this.idEntity = idEntity;
    }

    public String getMediaType() {
        return this.mediaType;
    }

    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getContactInformation() {
        return this.contactInformation;
    }

    public void setContactInformation(String contactInformation) {
        this.contactInformation = contactInformation;
    }

    public String getEmbedCode() {
        return this.embedCode;
    }

    public void setEmbedCode(String embedCode) {
        this.embedCode = embedCode;
    }

    public String getUri() {
        return this.uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
