package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * MusicVO generated by hbm2java
 */
@XmlRootElement(name = "music")
public class MusicVO implements java.io.Serializable {
	
	public static final String FLAG_MODERATE = "S";
    public static final String FLAG_NO_MODERATE = "N";
    public static final String FLAG_PUBLIC = "S";
    public static final String FLAG_NO_PUBLIC = "N";
	
    private static final long serialVersionUID = 1L;
    private Long idMusic;
    private ArtistVO artist;
    private String title;
    private Date dtRelease;
    private Long idCountry;
    private String uri;
    private String url;
    private Set<MusicArtistVO> musicArtistVOs = new HashSet<MusicArtistVO>(0);
    private Set<LyricVO> lyrics = new HashSet<LyricVO>(0);
    private AlbumVO album;
    private List<TagVO> styles = new ArrayList<TagVO>(0);
    private List<TagVO> freeStyles = new ArrayList<TagVO>(0);
    private Long idLyricOriginal;
    
    private String flag_moderate = FLAG_NO_MODERATE;
    private String flag_public = FLAG_PUBLIC;

    public void addStyle(String styleName) {
    	TagVO tagStyle = new TagVO();
    	tagStyle.setName(styleName);
    	tagStyle.setType(TagVO.TAG_TYPE_STYLE);
		styles.add(tagStyle);
    }
    
    public List<TagVO> getStyles() {
		return styles;
	}

	public void setStyles(List<TagVO> styles) {
		this.styles = styles;
	}

    public void addFreeStyle(String styleName) {
        TagVO tagStyle = new TagVO();
        tagStyle.setName(styleName);
        tagStyle.setType(TagVO.TAG_TYPE_FREESTYLE);
        styles.add(tagStyle);
    }
    
    public List<TagVO> getFreeStyles() {
        return freeStyles;
    }

    public void setFreeStyles(List<TagVO> freeStyles) {
        this.freeStyles = freeStyles;
    }

    public AlbumVO getAlbum() {
		return album;
	}

	public void setAlbum(AlbumVO album) {
		this.album = album;
	}

	public MusicVO() {
    }

    public MusicVO(ArtistVO artist) {
        this.artist = artist;
    }

    public MusicVO(ArtistVO artist, String title, Date dtRelease, Long idCountry, String uri, String url,
    		String flag_moderate, String flag_public, Set<MusicArtistVO> musicArtistVOs, Set<LyricVO> lyrics) {
        this.artist = artist;
        this.title = title;
        this.dtRelease = dtRelease;
        this.idCountry = idCountry;
        this.uri = uri;
        this.url = url;
        this.flag_moderate = flag_moderate;
        this.flag_public = flag_public;
        this.musicArtistVOs = musicArtistVOs;
        this.lyrics = lyrics;
    }

    public Long getIdMusic() {
        return this.idMusic;
    }

    public void setIdMusic(Long idMusic) {
        this.idMusic = idMusic;
    }

    public ArtistVO getArtist() {
        return this.artist;
    }

    public void setArtist(ArtistVO artist) {
        this.artist = artist;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getDtRelease() {
        return this.dtRelease;
    }

    public void setDtRelease(Date dtRelease) {
        this.dtRelease = dtRelease;
    }

    public Long getIdCountry() {
        return this.idCountry;
    }

    public void setIdCountry(Long idCountry) {
        this.idCountry = idCountry;
    }

    public String getUri() {
        return this.uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
    public String getFlag_moderate() {
		return flag_moderate;
	}

	public void setFlag_moderate(String flagModerate) {
		flag_moderate = flagModerate;
	}

	public String getFlag_public() {
		return flag_public;
	}

	public void setFlag_public(String flagPublic) {
		flag_public = flagPublic;
	}
    public Set<MusicArtistVO> getMusicArtists() {
        return this.musicArtistVOs;
    }

    public void setMusicArtists(Set<MusicArtistVO> musicArtistVOs) {
        this.musicArtistVOs = musicArtistVOs;
    }
    
    public void addComposer(String name) {
    	ArtistVO composer = new ArtistVO();
    	composer.setName(name);

    	MusicArtistVO musicArtistVO = new MusicArtistVO();
		musicArtistVO.setArtist(composer);
		MusicVO musicOnlyId = new MusicVO();
		musicOnlyId.setIdMusic(this.getIdMusic());
		//MusicVO musicOnlyId = (MusicVO) CloneUtil.clone(this);
		//musicOnlyId.setAlbum(null);
		//musicOnlyId.setArtist(null);
		//musicOnlyId.setLyric(null);
		//musicOnlyId.setMusicArtists(null);
		//musicOnlyId.setStyles(null);
		musicArtistVO.setMusic(musicOnlyId);
		musicArtistVO.setParticipation(MusicArtistVO.PARTICIPATION_COMPOSER);

		this.musicArtistVOs.add(musicArtistVO);
    }

    public Set<LyricVO> getLyrics() {
        return this.lyrics;
    }

    public void setLyrics(Set<LyricVO> lyrics) {
        this.lyrics = lyrics;
    }
    
    public Long getIdLyricOriginal() {
		return idLyricOriginal;
	}

	public void setIdLyricOriginal(Long idLyricOriginal) {
		this.idLyricOriginal = idLyricOriginal;
	}

    @XmlTransient
    public LyricVO getModeratedLyric() {
        if (lyrics != null && !lyrics.isEmpty()) {
            for(Iterator<LyricVO> it = lyrics.iterator(); it.hasNext(); ){
            	LyricVO lyricVO = it.next();
            	if(lyricVO != null && lyricVO.getFlag() != null && lyricVO.getFlag().equals(LyricVO.FLAG_DEFAULT)) {
            		return lyricVO;
            	}
            }
        }
    	return new LyricVO();
    }
    
    @XmlTransient
    public LyricVO getModeratedLyricDefault() {
        if (lyrics != null && !lyrics.isEmpty()) {
            for(Iterator<LyricVO> it = lyrics.iterator(); it.hasNext(); ){
            	LyricVO lyricVO = it.next();
            	 
            	if(lyricVO != null && lyricVO.getFlag() != null){
            		if(lyricVO.getFlag().equals(LyricVO.FLAG_DEFAULT)) {
            			return lyricVO;
            		}else if(lyricVO.getFlag().equals(LyricVO.FLAG_NO_DEFAULT) && !it.hasNext()){
            			return lyricVO;
            		}
            	}
            }
         }
       	return new LyricVO();
    }

    /**
     * @return Se existe ou nao uma letra exibivel
     */
    public boolean hasModeratedLyric() {
        if (lyrics != null && !lyrics.isEmpty()) {
            for(Iterator<LyricVO> it = lyrics.iterator(); it.hasNext(); ){
                LyricVO lyricVO = it.next();
                if(lyricVO != null && lyricVO.getFlag() != null && lyricVO.getFlag().equals(LyricVO.FLAG_DEFAULT)) {
                    return true;
                }
            }
        }
        return false;
    }

    public void addLyric(LyricVO lyric) {
        this.lyrics.add(lyric);
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "MusicVO [flag_moderate=" + flag_moderate + ", flag_public="
				+ flag_public + ", title=" + title + "]";
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     
    @Override
    public String toString() {
        return "MusicVO [" + (album != null ? "album=" + album + ", " : "") + (artist != null ? "artist=" + artist + ", " : "")
                + (dtRelease != null ? "dtRelease=" + dtRelease + ", " : "") + (idCountry != null ? "idCountry=" + idCountry + ", " : "")
                + (idMusic != null ? "idMusic=" + idMusic + ", " : "") + (lyrics != null ? "lyrics=" + lyrics + ", " : "")
                + (musicArtistVOs != null ? "musicArtistVOs=" + musicArtistVOs + ", " : "") + (styles != null ? "styles=" + styles + ", " : "")
                + (title != null ? "title=" + title + ", " : "") + (uri != null ? "uri=" + uri + ", " : "") + (url != null ? "url=" + url : "") + "]";
    }
*/
    
}
