package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import javax.xml.bind.annotation.XmlRootElement;

/**
 * MusicArtistId generated by hbm2java
 */
@XmlRootElement
public class MusicArtistId implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private long idMusic;
    private long idArtist;
    private String participation;

    public MusicArtistId() {
    }

    public MusicArtistId(long idMusic, long idArtist) {
        this.idMusic = idMusic;
        this.idArtist = idArtist;
    }

    public MusicArtistId(long idMusic, long idArtist, String participation) {
        this.idMusic = idMusic;
        this.idArtist = idArtist;
        this.participation = participation;
    }

    public long getIdMusic() {
        return this.idMusic;
    }

    public void setIdMusic(long idMusic) {
        this.idMusic = idMusic;
    }

    public long getIdArtist() {
        return this.idArtist;
    }

    public void setIdArtist(long idArtist) {
        this.idArtist = idArtist;
    }

    public String getParticipation() {
        return this.participation;
    }

    public void setParticipation(String participation) {
        this.participation = participation;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof MusicArtistId))
            return false;
        MusicArtistId castOther = (MusicArtistId) other;

        return (this.getIdMusic() == castOther.getIdMusic())
                && (this.getIdArtist() == castOther.getIdArtist())
                && ((this.getParticipation() == castOther.getParticipation()) || (this.getParticipation() != null
                        && castOther.getParticipation() != null && this.getParticipation().equals(castOther.getParticipation())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getIdMusic();
        result = 37 * result + (int) this.getIdArtist();
        result = 37 * result + (getParticipation() == null ? 0 : this.getParticipation().hashCode());
        return result;
    }

}
