package br.com.tamandua.service.vo;

// Generated 21/02/2010 23:04:42 by Hibernate Tools 3.2.4.GA

import javax.xml.bind.annotation.XmlRootElement;

/**
 * TagVO generated by hbm2java
 */
@XmlRootElement(name = "tag")
public class TagVO implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
	
    public static final String TAG_TYPE_STYLE = "STYLE";
	public static final String TAG_TYPE_FREESTYLE = "FREESTYLE";
	public static final String TAG_TYPE_PHOTO_ALBUM = "PHOTO_ALBUM";
	public static final String TAG_TYPE_LABEL = "LABEL";
	public static final String TAG_TYPE_SENTIMENT = "SENTIMENT";

	private Long idTag;
    private EntityDescriptorVO entityDescriptor;
    private String description;
    private String owner;
    private String name;
    private Long idEntity;
    private String type;

    public TagVO() {
    }

    public TagVO(EntityDescriptorVO entityDescriptor) {
        this.entityDescriptor = entityDescriptor;
    }

    public TagVO(EntityDescriptorVO entityDescriptor, String description, String owner, String name, Long idEntity, String type) {
        this.entityDescriptor = entityDescriptor;
        this.description = description;
        this.owner = owner;
        this.name = name;
        this.idEntity = idEntity;
        this.type = type;
    }

    public Long getIdTag() {
        return this.idTag;
    }

    public void setIdTag(Long idTag) {
        this.idTag = idTag;
    }

    public EntityDescriptorVO getEntityDescriptor() {
        return this.entityDescriptor;
    }

    public void setEntityDescriptor(EntityDescriptorVO entityDescriptor) {
        this.entityDescriptor = entityDescriptor;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getOwner() {
        return this.owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getIdEntity() {
        return this.idEntity;
    }

    public void setIdEntity(Long idEntity) {
        this.idEntity = idEntity;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
